package telran.ashkelon2018.rent.dto;

public enum CarsReturnCode {
	OK, MODEL_EXISTS, CAR_EXISTS, DRIVER_EXISTS, NO_MODEL, NO_DRIVER, NO_CAR, CAR_IN_USE, CAR_NOT_EXISTS, CAR_NOT_RENTED, RETURN_DATE_WRONG
}
